// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aytytkuujeptbztuzazm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dHl0a3V1amVwdGJ6dHV6YXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTQ0MjgsImV4cCI6MjA2OTI3MDQyOH0.A8tz8EH1iD1Z_ytl-1s1EgjBzIs2TOV1c7RJfhoNkW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});